name: Lint

on: [push, pull_request]

jobs:
  phpcs:
    name: PHP Code Sniffer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: none
          tools: phpcs

      - name: Install dependencies
        run: composer install --no-interaction --no-progress

      - name: Run PHP_CodeSniffer
        run: |
          vendor/bin/phpcs --standard=phpcs.xml
